$ANSIBLE_VAULT;1.1;AES256
61626263323138396135633361663764383661366635663638323061383633633264333839633638
3738616463333662343965313965643862643236623230330a343066633031333064633938613332
33366562366333346465636364373433326663303138373830633964363338373834623535616535
3866343338616666640a643139366133653739326538646664343365653461353434666135316235
61663665633130326530393963323430316439393264326332356566633561646430623361326563
62623733393832613932386631613035653530623136316331393137353264306236353938313161
32363736346332663739656566333236663636323734303433306235336232373735326638333133
39353565303036303064643638666334396133646235613036613466666665303636333732323862
64366231333665643963636561666163333930303631643233633665366463323333633839336466
33393966343934326661333732383564303738613162613238343264386435343734653739623063
32303037323565626438656332653765393634626333373464373866643139333937633432623664
30333566343432363165613866313638643439313366663135356539306461653633393862396362
30333566326563376265363162313963313536313065636435326537633139316638663535616532
32613762316438316139306133373762333161343464646436663839333262356535393431363236
633865373865646166636633656164666463
